# Generated by Django 5.1.2 on 2024-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_itemcategory_item_store_storeitemreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="purchase_interval_days",
        ),
        migrations.RemoveField(
            model_name="itemcategory",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="store",
            name="travel_time_home_min",
        ),
        migrations.RemoveField(
            model_name="storeitemreference",
            name="price_per_unit",
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="unit_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storeitemreference",
            name="unit_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="storeitemreference",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
