# Generated by Django 5.1.2 on 2024-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0007_alter_item_name_alter_purchasehistory_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="travel_time_home_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="自宅からの移動時間（分）"
            ),
        ),
    ]
