# Generated by Django 5.1.2 on 2024-11-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0010_alter_storetraveltime_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="last_purchase_date",
            field=models.DateField(blank=True, null=True, verbose_name="最終購入日"),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_interval_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="購入頻度（日）"
            ),
        ),
    ]
