# Generated by Django 5.1.2 on 2024-11-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0012_shoppinglist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="last_purchase_date",
        ),
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="unit_quantity",
        ),
    ]
