# Generated by Django 5.1.2 on 2024-11-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0013_remove_item_last_purchase_date_remove_item_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeitemreference",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="storeitemreference",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="storeitemreference",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_references",
                to="App.item",
            ),
        ),
        migrations.AlterField(
            model_name="storeitemreference",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="storeitemreference",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_references",
                to="App.store",
            ),
        ),
    ]
