# Generated by Django 5.1.2 on 2024-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0014_remove_storeitemreference_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitemreference",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
