# Generated by Django 5.1.2 on 2024-11-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0015_alter_storeitemreference_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="価格")),
                ("unit_quantity", models.IntegerField(verbose_name="入数")),
                (
                    "memo",
                    models.CharField(blank=True, max_length=100, verbose_name="メモ"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="App.store",
                    ),
                ),
            ],
        ),
    ]
