# Generated by Django 5.1.2 on 2024-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0016_storeprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=50, verbose_name="店舗名"),
        ),
    ]
