# Generated by Django 5.1.2 on 2024-11-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0017_alter_store_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprice",
            name="item",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="App.item"
            ),
        ),
    ]
