# Generated by Django 5.1.2 on 2024-11-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0018_storeprice_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeprice",
            name="item",
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
