# Generated by Django 5.1.2 on 2024-12-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0025_rename_category_itemcategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemCategory",
            new_name="Category",
        ),
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
    ]
