# Generated by Django 5.1.2 on 2024-12-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0027_rename_category_itemcategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_purchase_quantity", models.IntegerField(default=0)),
                ("purchased_quantity", models.IntegerField(blank=True, null=True)),
                ("purchased_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.item"
                    ),
                ),
            ],
        ),
    ]
