# Generated by Django 5.1.2 on 2024-12-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0029_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitemreference",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="価格"),
        ),
        migrations.AlterField(
            model_name="storeitemreference",
            name="price_per_unit",
            field=models.IntegerField(blank=True, null=True, verbose_name="単位数"),
        ),
    ]
