# Generated by Django 5.1.2 on 2024-12-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0030_alter_storeitemreference_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="purchased_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
