# Generated by Django 5.1.2 on 2025-01-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0031_alter_purchasehistory_purchased_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeitemreference",
            name="no_price",
            field=models.BooleanField(default=False, verbose_name="取り扱いなし"),
        ),
        migrations.AddField(
            model_name="storeitemreference",
            name="price_unknown",
            field=models.BooleanField(default=False, verbose_name="価格不明"),
        ),
    ]
