# Generated by Django 5.1.2 on 2025-02-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0032_storeitemreference_no_price_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storeitemreference",
            unique_together={("store", "item")},
        ),
    ]
