# Generated by Django 5.1.2 on 2025-02-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0033_alter_storeitemreference_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storeitemreference",
            unique_together=set(),
        ),
    ]
