# Generated by Django 5.1.2 on 2025-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0034_alter_storeitemreference_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeitemreference",
            name="no_price",
        ),
        migrations.AddField(
            model_name="storeitemreference",
            name="no_handling",
            field=models.BooleanField(default=False, verbose_name="取り扱いなし"),
        ),
    ]
