# Generated by Django 5.1.2 on 2025-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0036_storetraveltime_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcategory",
            name="display_order",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="storeitemreference",
            unique_together={("store", "item")},
        ),
    ]
