# Generated by Django 5.1.2 on 2025-03-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0037_alter_itemcategory_display_order_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storeitemreference",
            unique_together=set(),
        ),
    ]
